# Generated by Django 2.2.3 on 2020-08-23 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bantitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_title', models.CharField(max_length=100, verbose_name='禁止タイトル')),
            ],
            options={
                'db_table': 'bantitle',
            },
        ),
        migrations.CreateModel(
            name='Banurl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_url', models.CharField(max_length=100, verbose_name='禁止URL')),
            ],
            options={
                'db_table': 'banurl',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_word', models.CharField(max_length=50, verbose_name='検索ワード')),
                ('search_dt', models.DateTimeField(verbose_name='期日')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
